local breadcrumb = {
	WinBar = {
		bg = Config.transparent_background and nil or C.editor.background,
		fg = C.breadcrumb.foreground,
	},
	BreadcrumbIconsArray = { fg = C.base.red },
	BreadcrumbIconsBoolean = { fg = C.base.red },
	BreadcrumbIconsClass = { fg = C.base.cyan },
	BreadcrumbIconsColor = { fg = C.base.magenta },
	BreadcrumbIconsConstant = { fg = C.base.magenta },
	BreadcrumbIconsConstructor = { fg = C.base.green },
	BreadcrumbIconsEnum = { fg = C.base.blue },
	BreadcrumbIconsEnumMember = { fg = C.base.blue },
	BreadcrumbIconsEvent = { fg = C.base.blue },
	BreadcrumbIconsField = { fg = C.base.blue },
	BreadcrumbIconsFile = { fg = C.editorLineNumber.activeForeground },
	BreadcrumbIconsFolder = { fg = C.editorLineNumber.activeForeground },
	BreadcrumbIconsFunction = { fg = C.base.green },
	BreadcrumbIconsInterface = { fg = C.base.cyan },
	BreadcrumbIconsKey = { fg = C.base.blue },
	BreadcrumbIconsKeyword = { fg = C.base.red },
	BreadcrumbIconsMethod = { fg = C.base.green },
	BreadcrumbIconsModule = { fg = C.base.cyan },
	BreadcrumbIconsNamespace = { fg = C.base.cyan },
	BreadcrumbIconsNull = { fg = C.base.magenta },
	BreadcrumbIconsNumber = { fg = C.base.magenta },
	BreadcrumbIconsObject = { fg = C.base.cyan },
	BreadcrumbIconsOperator = { fg = C.base.red },
	BreadcrumbIconsPackage = { fg = C.base.magenta },
	BreadcrumbIconsProperty = { fg = C.base.blue },
	BreadcrumbIconsReference = { fg = C.base.magenta },
	BreadcrumbIconsSnippet = { fg = C.base.green },
	BreadcrumbIconsString = { fg = C.base.yellow },
	BreadcrumbIconsStruct = { fg = C.base.red },
	BreadcrumbIconsText = { fg = C.base.yellow },
	BreadcrumbIconsTypeParameter = { fg = C.base.blue },
	BreadcrumbIconsUnit = { fg = C.base.magenta },
	BreadcrumbIconsVariable = { fg = C.base.cyan },
}

return breadcrumb
