local breadcrumb = {
	BreadcrumbIconsArray = { fg = C.red },
	BreadcrumbIconsBoolean = { fg = C.red },
	BreadcrumbIconsClass = { fg = C.cyan },
	BreadcrumbIconsColor = { fg = C.magenta },
	BreadcrumbIconsConstant = { fg = C.magenta },
	BreadcrumbIconsConstructor = { fg = C.green },
	BreadcrumbIconsEnum = { fg = C.blue },
	BreadcrumbIconsEnumMember = { fg = C.blue },
	BreadcrumbIconsEvent = { fg = C.blue },
	BreadcrumbIconsField = { fg = C.blue },
	BreadcrumbIconsFile = { fg = C.lineNumberActiveForeground },
	BreadcrumbIconsFolder = { fg = C.lineNumberActiveForeground },
	BreadcrumbIconsFunction = { fg = C.green },
	BreadcrumbIconsInterface = { fg = C.cyan },
	BreadcrumbIconsKey = { fg = C.blue },
	BreadcrumbIconsKeyword = { fg = C.red },
	BreadcrumbIconsMethod = { fg = C.green },
	BreadcrumbIconsModule = { fg = C.cyan },
	BreadcrumbIconsNamespace = { fg = C.cyan },
	BreadcrumbIconsNull = { fg = C.magenta },
	BreadcrumbIconsNumber = { fg = C.magenta },
	BreadcrumbIconsObject = { fg = C.cyan },
	BreadcrumbIconsOperator = { fg = C.red },
	BreadcrumbIconsPackage = { fg = C.magenta },
	BreadcrumbIconsProperty = { fg = C.blue },
	BreadcrumbIconsReference = { fg = C.magenta },
	BreadcrumbIconsSnippet = { fg = C.green },
	BreadcrumbIconsString = { fg = C.yellow },
	BreadcrumbIconsStruct = { fg = C.red },
	BreadcrumbIconsText = { fg = C.yellow },
	BreadcrumbIconsTypeParameter = { fg = C.blue },
	BreadcrumbIconsUnit = { fg = C.magenta },
	BreadcrumbIconsVariable = { fg = C.cyan },
}

return breadcrumb
