local Cmp = {
	CmpItemAbbrMatch = { fg = C.suggestWidgetHighlightForeground, style = "bold" },

	CmpItemAbbrDeprecated = { fg = C.lightBlack, style = "strikethrough" },
	CmpItemAbbrMatchFuzzy = { fg = C.blue },
	CmpItemKindFunction = { fg = C.magenta },
	CmpItemKindMethod = { fg = C.magenta },
	CmpItemKindConstructor = { fg = C.blue },
	CmpItemKindClass = { fg = C.blue },
	CmpItemKindEnum = { fg = C.blue },
	CmpItemKindEvent = { fg = C.magenta },
	CmpItemKindInterface = { fg = C.cyan },
	CmpItemKindStruct = { fg = C.cyan },
	CmpItemKindVariable = { fg = C.cyan },
	CmpItemKindField = { fg = C.cyan },
	CmpItemKindProperty = { fg = C.cyan },
	CmpItemKindEnumMember = { fg = C.cyan },
	CmpItemKindConstant = { fg = C.cyan },
	CmpItemKindKeyword = { fg = C.cyan },
	CmpItemKindModule = { fg = C.lightWhite },
	CmpItemKindValue = { fg = C.lightWhite },
	CmpItemKindUnit = { fg = C.lightWhite },
	CmpItemKindText = { fg = C.lightWhite },
	CmpItemKindSnippet = { fg = C.lightWhite },
	CmpItemKindFile = { fg = C.lightWhite },
	CmpItemKindFolder = { fg = C.lightWhite },
	CmpItemKindColor = { fg = C.lightWhite },
	CmpItemKindReference = { fg = C.lightWhite },
	CmpItemKindOperator = { fg = C.lightWhite },
	CmpItemKindTypeParameter = { fg = C.lightWhite },
}

return Cmp
