local Cmp = {
	CmpItemAbbrMatch = { fg = C.suggestWidgetHighlightForeground, style = "bold" },

	CmpItemAbbrDeprecated = { fg = C.lightBlack, style = "strikethrough" },
	CmpItemAbbrMatchFuzzy = { fg = C.blue },

	CmpItemKindArray = { fg = C.red },
	CmpItemKindBoolean = { fg = C.red },
	CmpItemKindClass = { fg = C.cyan },
	CmpItemKindColor = { fg = C.magenta },
	CmpItemKindConstant = { fg = C.magenta },
	CmpItemKindConstructor = { fg = C.green },
	CmpItemKindEnum = { fg = C.blue },
	CmpItemKindEnumMember = { fg = C.blue },
	CmpItemKindEvent = { fg = C.blue },
	CmpItemKindField = { fg = C.blue },
	CmpItemKindFile = { fg = C.lineNumberActiveForeground },
	CmpItemKindFolder = { fg = C.lineNumberActiveForeground },
	CmpItemKindFunction = { fg = C.green },
	CmpItemKindInterface = { fg = C.cyan },
	CmpItemKindKey = { fg = C.blue },
	CmpItemKindKeyword = { fg = C.red },
	CmpItemKindMethod = { fg = C.green },
	CmpItemKindModule = { fg = C.cyan },
	CmpItemKindNamespace = { fg = C.cyan },
	CmpItemKindNull = { fg = C.magenta },
	CmpItemKindNumber = { fg = C.magenta },
	CmpItemKindObject = { fg = C.cyan },
	CmpItemKindOperator = { fg = C.red },
	CmpItemKindPackage = { fg = C.magenta },
	CmpItemKindProperty = { fg = C.blue },
	CmpItemKindReference = { fg = C.magenta },
	CmpItemKindSnippet = { fg = C.green },
	CmpItemKindString = { fg = C.yellow },
	CmpItemKindStruct = { fg = C.red },
	CmpItemKindText = { fg = C.yellow },
	CmpItemKindTypeParameter = { fg = C.blue },
	CmpItemKindUnit = { fg = C.magenta },
	CmpItemKindVariable = { fg = C.cyan },
}

return Cmp
