local markdown = {
	markdownBlockquote = { fg = C.green },
	markdownCode = { fg = C.blue },
	markdownCodeBlock = { fg = C.blue },
	markdownCodeDelimiter = { fg = C.blue },
	markdownH1 = { fg = C.blue },
	markdownH2 = { fg = C.blue },
	markdownH3 = { fg = C.blue },
	markdownH4 = { fg = C.blue },
	markdownH5 = { fg = C.blue },
	markdownH6 = { fg = C.blue },
	markdownHeadingDelimiter = { fg = C.blue },
	markdownHeadingRule = { fg = C.white, style = "bold" },
	markdownId = { fg = C.magenta },
	markdownIdDeclaration = { fg = C.cyan },
	markdownIdDelimiter = { fg = C.lightBlack },
	markdownLinkDelimiter = { fg = C.lightBlack },
	markdownBold = { fg = C.cyan, style = "bold" },
	markdownItalic = { style = "italic" },
	markdownBoldItalic = { fg = C.blue, style = "bold,italic" },
	markdownListMarker = { fg = C.cyan },
	markdownOrderedListMarker = { fg = C.cyan },
	markdownRule = { fg = C.lightGray },
	markdownUrl = { fg = C.cyan, style = "underline" },
	markdownLinkText = { fg = C.cyan },
	markdownFootnote = { fg = C.blue },
	markdownFootnoteDefinition = { fg = C.blue },
	markdownEscape = { fg = C.blue },
}

return markdown
