local NvimTree = {
	NvimTreeFolderIcon = { fg = C.green },
	NvimTreeIndentMarker = { fg = "#606060" },
	NvimTreeNormal = { fg = C.lightWhite, bg = C.black },
	NvimTreeVertSplit = { fg = C.black, bg = C.black },
	NvimTreeFolderName = { fg = C.green },
	NvimTreeOpenedFolderName = { fg = C.yellow, style = "italic" },
	NvimTreeEmptyFolderName = { fg = C.lighBlack, style = "italic" },
	NvimTreeGitIgnored = { fg = C.lighBlack, style = "italic" },
	NvimTreeImageFile = { fg = C.lightWhite },
	NvimTreeSpecialFile = { fg = C.blue },
	NvimTreeEndOfBuffer = { fg = C.black },
	NvimTreeCursorLine = { bg = "#2A2D2E" },
	NvimTreeGitignoreIcon = { fg = "#E64A19" },
	NvimTreeGitStaged = { fg = C.green },
	NvimTreeGitNew = { fg = C.green },
	NvimTreeGitRenamed = { fg = C.green },
	NvimTreeGitDeleted = { fg = C.red },
	NvimTreeGitMerge = { fg = C.cyan },
	NvimTreeGitDirty = { fg = C.cyan },
	NvimTreeSymlink = { fg = C.lightCyan },
	NvimTreeRootFolder = { fg = C.white, style = "bold" },
	NvimTreeExecFile = { fg = "#9FBA89" },
}

return NvimTree
