local NvimTree = {
	NvimTreeFolderIcon = { fg = C.base.green },
	NvimTreeIndentMarker = { fg = "#606060" },
	NvimTreeNormal = { fg = C.base.lightWhite, bg = C.base.black },
	NvimTreeVertSplit = { fg = C.base.black, bg = C.base.black },
	NvimTreeFolderName = { fg = C.base.green },
	NvimTreeOpenedFolderName = { fg = C.base.yellow, italic = true },
	NvimTreeEmptyFolderName = { fg = C.base.lightBlack, italic = true },
	NvimTreeGitIgnored = { fg = C.base.lightBlack, italic = true },
	NvimTreeImageFile = { fg = C.base.lightWhite },
	NvimTreeSpecialFile = { fg = C.base.blue },
	NvimTreeEndOfBuffer = { fg = C.base.black },
	NvimTreeCursorLine = { bg = "#2A2D2E" },
	NvimTreeGitignoreIcon = { fg = "#E64A19" },
	NvimTreeGitStaged = { fg = C.base.green },
	NvimTreeGitNew = { fg = C.base.green },
	NvimTreeGitRenamed = { fg = C.base.green },
	NvimTreeGitDeleted = { fg = C.base.red },
	NvimTreeGitMerge = { fg = C.base.cyan },
	NvimTreeGitDirty = { fg = C.base.cyan },
	NvimTreeSymlink = { fg = C.base.lightCyan },
	NvimTreeRootFolder = { fg = C.base.white, bold = true },
	NvimTreeExecFile = { fg = "#9FBA89" },
}

return NvimTree
