local nvim_navic = {
	NavicIconsArray = { fg = C.base.red },
	NavicIconsBoolean = { fg = C.base.red },
	NavicIconsClass = { fg = C.base.cyan },
	NavicIconsColor = { fg = C.base.magenta },
	NavicIconsConstant = { fg = C.base.magenta },
	NavicIconsConstructor = { fg = C.base.green },
	NavicIconsEnum = { fg = C.base.blue },
	NavicIconsEnumMember = { fg = C.base.blue },
	NavicIconsEvent = { fg = C.base.blue },
	NavicIconsField = { fg = C.base.blue },
	NavicIconsFile = { fg = C.editorLineNumber.activeForeground },
	NavicIconsFolder = { fg = C.editorLineNumber.activeForeground },
	NavicIconsFunction = { fg = C.base.green },
	NavicIconsInterface = { fg = C.base.cyan },
	NavicIconsKey = { fg = C.base.blue },
	NavicIconsKeyword = { fg = C.base.red },
	NavicIconsMethod = { fg = C.base.green },
	NavicIconsModule = { fg = C.base.cyan },
	NavicIconsNamespace = { fg = C.base.cyan },
	NavicIconsNull = { fg = C.base.magenta },
	NavicIconsNumber = { fg = C.base.magenta },
	NavicIconsObject = { fg = C.base.cyan },
	NavicIconsOperator = { fg = C.base.red },
	NavicIconsPackage = { fg = C.base.magenta },
	NavicIconsProperty = { fg = C.base.blue },
	NavicIconsReference = { fg = C.base.magenta },
	NavicIconsSnippet = { fg = C.base.green },
	NavicIconsString = { fg = C.base.yellow },
	NavicIconsStruct = { fg = C.base.red },
	NavicIconsText = { fg = C.base.yellow },
	NavicIconsTypeParameter = { fg = C.base.blue },
	NavicIconsUnit = { fg = C.base.magenta },
	NavicIconsVariable = { fg = C.base.cyan },
}

return nvim_navic
