local winbar = {
	WinbarIconsArray = { fg = C.red },
	WinbarIconsBoolean = { fg = C.red },
	WinbarIconsClass = { fg = C.cyan },
	WinbarIconsColor = { fg = C.magenta },
	WinbarIconsConstant = { fg = C.magenta },
	WinbarIconsConstructor = { fg = C.green },
	WinbarIconsEnum = { fg = C.blue },
	WinbarIconsEnumMember = { fg = C.blue },
	WinbarIconsEvent = { fg = C.blue },
	WinbarIconsField = { fg = C.blue },
	WinbarIconsFile = { fg = C.lineNumberActiveForeground },
	WinbarIconsFolder = { fg = C.lineNumberActiveForeground },
	WinbarIconsFunction = { fg = C.green },
	WinbarIconsInterface = { fg = C.cyan },
	WinbarIconsKey = { fg = C.blue },
	WinbarIconsKeyword = { fg = C.red },
	WinbarIconsMethod = { fg = C.green },
	WinbarIconsModule = { fg = C.cyan },
	WinbarIconsNamespace = { fg = C.cyan },
	WinbarIconsNull = { fg = C.magenta },
	WinbarIconsNumber = { fg = C.magenta },
	WinbarIconsObject = { fg = C.cyan },
	WinbarIconsOperator = { fg = C.red },
	WinbarIconsPackage = { fg = C.magenta },
	WinbarIconsProperty = { fg = C.blue },
	WinbarIconsReference = { fg = C.magenta },
	WinbarIconsSnippet = { fg = C.green },
	WinbarIconsString = { fg = C.yellow },
	WinbarIconsStruct = { fg = C.red },
	WinbarIconsText = { fg = C.yellow },
	WinbarIconsTypeParameter = { fg = C.blue },
	WinbarIconsUnit = { fg = C.magenta },
	WinbarIconsVariable = { fg = C.cyan },
}

return winbar
