local highlights = {
	Normal = { fg = C.base1F, bg = C.base00 },
	CursorLine = { bg = C.base03 },
	EndOfBuffer = { fg = C.base00, bg = Config.transparent_background and "NONE" or C.base00 },
	SignColumn = { bg = Config.transparent_background and "NONE" or C.base00 },
	LineNr = { fg = C.base13 },
	CursorLineNr = { fg = C.base1D, style = "bold" },
	Pmenu = { fg = C.base1E, bg = C.base07 },
	PmenuSel = { fg = C.base1E, bg = C.base0A },
	PmenuThumb = { bg = C.base0F },
	NormalFloat = { bg = C.base0B }, -- Packer Normal
	FloatBorder = { fg = C.base0B, bg = C.base0B },
	Visual = { bg = C.base04 },
	Offset = { fg = C.base1C, bg = C.base03 },
	illuminatedWord = { bg = C.base07 },
	TermBorder = { fg = C.base13, bg = C.base00 },
  TermNormal = { bg = C.base00 },
	Folded = { fg = C.base1E, bg = C.base01 },
	FoldColumn = { fg = C.base1C, bg = C.base00 },
	VertSplit = { fg = "#34352F", bg = C.base00 },
	InlayHint = { fg = C.base0A, style = "italic" },

	MsgArea = { fg = C.base1F, bg = Config.transparent_background and "NONE" or C.base00 },
	ModeMsg = { fg = C.base1F, bg = C.base00 },
	MsgSeparator = { fg = C.base1F, bg = C.base00 },
	SpellBad = { fg = C.base0D, style = "underline" },
	SpellCap = { fg = C.base18, style = "underline" },
	SpellLocal = { fg = C.base14, style = "underline" },
	SpellRare = { fg = C.base10, style = "underline" },
	NormalNC = { fg = C.base1F, bg = Config.transparent_background and "NONE" or C.base00 },
	WildMenu = { fg = C.base1F, bg = C.base0A },
	Comment = { fg = C.base0E, style = "italic" },
	WhiteEspace = { fg = C.base00 },
	CursorColumn = { bg = C.base00 },
	ColorColumn = { bg = C.base00 },
	VisualNOS = { bg = C.base03 },
	WarningMsg = { fg = C.base0D, bg = C.base00 },
	DiffAdd = { fg = C.base03, bg = C.base15 },
	DiffChange = { fg = C.base03, bg = C.base11, style = "underline" },
	DiffDelete = { fg = C.base03, bg = C.base0D },
	QuickFixLine = { bg = C.base0A },
	PmenuSbar = { bg = C.base03 },
	MatchWord = { style = "underline" },
	MatchParen = { fg = C.base19, bg = C.base00, style = "underline" },
	MatchWordCur = { style = "underline" },
	MatchParenCur = { style = "underline" },
	Cursor = { fg = C.base08, bg = C.base08 },
	lCursor = { fg = C.base08, bg = C.base08 },
	CursorIM = { fg = C.base08, bg = C.base08 },
	TermCursor = { fg = C.base19, bg = C.base08 },
	TermCursorNC = { fg = C.base08, bg = C.base08 },
	Conceal = { fg = C.base1C },
	Directory = { fg = C.base19 },
	SpecialKey = { fg = C.base19, style = "bold" },
	Title = { fg = C.base19, style = "bold" },
	ErrorMsg = { fg = C.base0D, bg = C.base00, style = "bold" },
	Search = { fg = C.base1E, bg = "#603113" },
	IncSearch = { fg = "#603113", bg = C.base1E },
	Substitute = { fg = C.base1E, bg = "#603113" },
	MoreMsg = { fg = C.base12 },
	Question = { fg = C.base12 },
	NonText = { fg = C.base00 },
	Variable = { fg = C.base19 },
	String = { fg = C.base12 },
	Character = { fg = C.base12 },
	Constant = { fg = C.base16 },
	Number = { fg = C.base15 },
	Boolean = { fg = C.base19 },
	Float = { fg = C.base05 },
	Identifier = { fg = C.base19 },
	Function = { fg = C.base18 },
	Operator = { fg = C.base1F },
	Type = { fg = C.base19 },
	StorageClass = { fg = C.base19 },
	Structure = { fg = C.base19 },
	Typedef = { fg = C.base19 },
	Keyword = { fg = C.base19 },
	Statement = { fg = C.base10 },
	Conditional = { fg = C.base19 },
	Repeat = { fg = C.base10 },
	Label = { fg = C.base10 },
	Exception = { fg = C.base10 },
	Include = { fg = C.base10 },
	PreProc = { fg = C.base10 },
	Define = { fg = C.base10 },
	Macro = { fg = C.base10 },
	PreCondit = { fg = C.base10 },
	Special = { fg = C.base12 },
	SpecialChar = { fg = C.base1E },
	Tag = { fg = C.base19 },
	Debug = { fg = C.base0D },
	Delimiter = { fg = C.base0E },
	SpecialComment = { fg = C.base0E, style="italic" },
	Underlined = { style = "underline" },
	Bold = { style = "bold" },
	Italic = { style = "italic" },
	Ignore = { fg = C.base19, bg = C.base00, style = "bold" },
	Todo = { fg = "#D16D9E", bg = C.base00, style = "bold" },
	Error = { fg = C.base0D, bg = C.base00, style = "bold" },
	TabLine = { fg = C.base1E, bg = C.base03 },
	TabLineSel = { fg = C.base1E, bg = C.base03 },
	TabLineFill = { fg = C.base03, bg = C.base03 },
}

return highlights
