local LSP = {
	LspDiagnosticsDefaultError = { fg = C.base0D },
	LspDiagnosticsDefaultWarning = { fg = C.base12 },
	LspDiagnosticsDefaultInformation = { fg = C.base18 },
	LspDiagnosticsDefaultInfo = { fg = C.base18 },
	LspDiagnosticsDefaultHint = { fg = C.base19 },
	LspDiagnosticsVirtualTextError = { fg = C.base0D },
	LspDiagnosticsVirtualTextWarning = { fg = C.base12 },
	LspDiagnosticsVirtualTextInformation = { fg = C.base18 },
	LspDiagnosticsVirtualTextInfo = { fg = C.base18 },
	LspDiagnosticsVirtualTextHint = { fg = C.base19 },
	LspDiagnosticsFloatingError = { fg = C.base0D },
	LspDiagnosticsFloatingWarning = { fg = C.base12 },
	LspDiagnosticsFloatingInformation = { fg = C.base18 },
	LspDiagnosticsFloatingInfo = { fg = C.base18 },
	LspDiagnosticsFloatingHint = { fg = C.base19 },
	DiagnosticSignError = { fg = C.base0D },
	DiagnosticSignWarning = { fg = C.base12 },
	DiagnosticSignInformation = { fg = C.base18 },
	DiagnosticSignInfo = { fg = C.base18 },
	DiagnosticSignHint = { fg = C.base19 },
	LspDiagnosticsSignError = { fg = C.base0D },
	LspDiagnosticsSignWarning = { fg = C.base12 },
	LspDiagnosticsSignInformation = { fg = C.base18 },
	LspDiagnosticsSignInfo = { fg = C.base18 },
	LspDiagnosticsSignHint = { fg = C.base19 },
	LspDiagnosticsError = { fg = C.base0D },
	LspDiagnosticsWarning = { fg = C.base12 },
	LspDiagnosticsInformation = { fg = C.base18 },
	LspDiagnosticsInfo = { fg = C.base18 },
	LspDiagnosticsHint = { fg = C.base19 },
	LspDiagnosticsUnderlineError = { style = "underline" },
	LspDiagnosticsUnderlineWarning = { style = "underline" },
	LspDiagnosticsUnderlineInformation = { style = "underline" },
	LspDiagnosticsUnderlineInfo = { style = "underline" },
	LspDiagnosticsUnderlineHint = { style = "underline" },
	LspReferenceRead = { bg = "#36383F" },
	LspReferenceText = { bg = "#36383F" },
	LspReferenceWrite = { bg = "#36383f" },
}

return LSP
