local markdown = {
	markdownBlockquote = { fg = C.base14 },
	markdownCode = { fg = C.base12 },
	markdownCodeBlock = { fg = C.base12 },
	markdownCodeDelimiter = { fg = C.base12 },
	markdownH1 = { fg = C.base16 },
	markdownH2 = { fg = C.base16 },
	markdownH3 = { fg = C.base16 },
	markdownH4 = { fg = C.base16 },
	markdownH5 = { fg = C.base16 },
	markdownH6 = { fg = C.base16 },
	markdownHeadingDelimiter = { fg = C.base16 },
	markdownHeadingRule = { fg = C.base1F, style = "bold" },
	markdownId = { fg = C.base10 },
	markdownIdDeclaration = { fg = C.base19 },
	markdownIdDelimiter = { fg = C.base0E },
	markdownLinkDelimiter = { fg = C.base0E },
	markdownBold = { fg = C.base19, style = "bold" },
	markdownItalic = { style = "italic" },
	markdownBoldItalic = { fg = C.base12, style = "bold,italic" },
	markdownListMarker = { fg = C.base19 },
	markdownOrderedListMarker = { fg = C.base19 },
	markdownRule = { fg = C.base1B },
	markdownUrl = { fg = C.base19, style = "underline" },
	markdownLinkText = { fg = C.base19 },
	markdownFootnote = { fg = C.base12 },
	markdownFootnoteDefinition = { fg = C.base12 },
	markdownEscape = { fg = C.base12 },
}

return markdown
