local Misc = {
	sassDefinition = { fg = C.base12 },
	sassProperty = { fg = C.base15 },
	cssProp = { fg = C.base15 },
	cssPositioningAttr = { fg = C.base19 },
	cssCustomProp = { fg = C.base1E },
	sassClass = { fg = C.base12 },

	sassInclude = { fg = C.base0D },
	cssStringQQ = { fg = C.base18 },
	sassAmpersand = { fg = C.base0D },
	cssPseudoClass = { fg = C.base14 },
	cssPseudoClassId = { fg = C.base14 },
	cssValueNumber = { fg = C.base10 },
	cssValueLength = { fg = C.base10 },
	cssUnitDecorators = { fg = C.base0D },
	cssPageProp = { fg = C.base0D },
	cssTagName = { fg = C.base0D },
	sassMixing = { fg = C.base0D },
	sassMixinName = { fg = C.base14 },
	sassCssAttribute = { fg = C.base10 },
	cssUIProp = { fg = C.base0D },

	diffAdded = { fg = C.base15 },
	diffRemoved = { fg = C.base0D },
	diffFileId = { fg = C.base19, style = "bold,reverse" },
	diffFile = { fg = C.base03 },
	diffNewFile = { fg = C.base14 },
	diffOldFile = { fg = C.base0D },
	debugPc = { bg = C.base11 },
	debugBreakpoint = { fg = C.base0D, style = "reverse" },
	CodiVirtualText = { fg = C.base19 },
	SniprunVirtualTextOk = { fg = C.base19 },
	SniprunFloatingWinOk = { fg = C.base19 },
	SniprunVirtualTextErr = { fg = C.base0D },
	SniprunFloatingWinErr = { fg = C.base0D },
	CompeDocumentation = { bg = C.base03 },
	DapBreakpoint = { fg = C.base0D },
	xmlTag = { fg = C.base19 },
	xmlTagName = { fg = C.base19 },
	xmlEndTag = { fg = C.base19 },
	yamlPlainScalar = { fg = C.base12 },
	yamlTSField = { fg = C.base19 },
	luaFunc = { fg = C.base18 },
	luaFunction = { fg = C.base19 },
	htmlH1 = { fg = C.base1F },
	htmlH2 = { fg = C.base1F },
	htmlH3 = { fg = C.base1F },
	htmlH4 = { fg = C.base1F },
	htmlH5 = { fg = C.base1F },
	htmlH6 = { fg = C.base1F },
	htmlHead = { fg = C.base1F },
	htmlTitle = { fg = C.base1F },
	htmlArg = { fg = C.base19 },
	htmlTag = { fg = C.base19 },
	htmlTagN = { fg = C.base19 },
	htmlTagName = { fg = C.base19 },
	htmlComment = { fg = C.base14 },
	htmlLink = { fg = C.base12, style = "underline" },
	cssBraces = { fg = C.base1F },
	cssInclude = { fg = C.base10 },
	cssClassName = { fg = C.base18 },
	cssPseudoClassLang = { fg = C.base18 },
	cssIdentifier = { fg = C.base18 },
	cssDefinition = { fg = C.base19 },
	cssAttrRegion = { fg = C.base12 },
	cssColor = { fg = C.base12 },
	cssFunction = { fg = C.base10 },
	cssFunctionName = { fg = C.base18 },
	cssVendor = { fg = C.base12 },
	cssStyle = { fg = C.base19 },
	cssImportant = { fg = C.base19 },
	jsonKeyword = { fg = C.base19 },
	yamlBlockMappingKey = { fg = C.base19 },
}

return Misc
