local Misc = {
	sassDefinition = { fg = C.orange },
	sassProperty = { fg = C.green },
	cssProp = { fg = C.green },
	cssPositioningAttr = { fg = C.cyan },
	cssCustomProp = { fg = C.lightGray },
	sassClass = { fg = C.orange },

	sassInclude = { fg = C.red },
	cssStringQQ = { fg = C.yellow },
	sassAmpersand = { fg = C.red },
	cssPseudoClass = { fg = C.lightGreen },
	cssPseudoClassId = { fg = C.lightGreen },
	cssValueNumber = { fg = C.magenta },
	cssValueLength = { fg = C.magenta },
	cssUnitDecorators = { fg = C.red },
	cssPageProp = { fg = C.red },
	cssTagName = { fg = C.red },
	sassMixing = { fg = C.red },
	sassMixinName = { fg = C.lightGreen },
	sassCssAttribute = { fg = C.magenta },
	cssUIProp = { fg = C.red },

	diffAdded = { fg = C.green },
	diffRemoved = { fg = C.red },
	diffFileId = { fg = C.cyan, style = "bold,reverse" },
	diffFile = { fg = C.black },
	diffNewFile = { fg = C.lightGreen },
	diffOldFile = { fg = C.red },
	debugPc = { bg = C.lightCyan },
	debugBreakpoint = { fg = C.red, style = "reverse" },
	CodiVirtualText = { fg = C.cyan },
	SniprunVirtualTextOk = { fg = C.cyan },
	SniprunFloatingWinOk = { fg = C.cyan },
	SniprunVirtualTextErr = { fg = C.red },
	SniprunFloatingWinErr = { fg = C.red },
	CompeDocumentation = { bg = C.black },
	DapBreakpoint = { fg = C.red },
	xmlTag = { fg = C.cyan },
	xmlTagName = { fg = C.cyan },
	xmlEndTag = { fg = C.cyan },
	yamlPlainScalar = { fg = C.orange },
	yamlTSField = { fg = C.cyan },
	luaFunc = { fg = C.yellow },
	luaFunction = { fg = C.cyan },
	htmlH1 = { fg = C.white },
	htmlH2 = { fg = C.white },
	htmlH3 = { fg = C.white },
	htmlH4 = { fg = C.white },
	htmlH5 = { fg = C.white },
	htmlH6 = { fg = C.white },
	htmlHead = { fg = C.white },
	htmlTitle = { fg = C.white },
	htmlArg = { fg = C.cyan },
	htmlTag = { fg = C.cyan },
	htmlTagN = { fg = C.cyan },
	htmlTagName = { fg = C.cyan },
	htmlComment = { fg = C.lightGreen },
	htmlLink = { fg = C.orange, style = "underline" },
	cssBraces = { fg = C.white },
	cssInclude = { fg = C.magenta },
	cssClassName = { fg = C.yellow },
	cssPseudoClassLang = { fg = C.yellow },
	cssIdentifier = { fg = C.yellow },
	cssDefinition = { fg = C.cyan },
	cssAttrRegion = { fg = C.orange },
	cssColor = { fg = C.orange },
	cssFunction = { fg = C.magenta },
	cssFunctionName = { fg = C.yellow },
	cssVendor = { fg = C.orange },
	cssStyle = { fg = C.cyan },
	cssImportant = { fg = C.cyan },
	jsonKeyword = { fg = C.cyan },
	yamlBlockMappingKey = { fg = C.cyan },
}

return Misc
