local Treesitter = {
	["@include"] = { fg = C.red },
	["@variable"] = { fg = C.white },
	["@punctuation.delimiter"] = { fg = C.lightGray },
	["@punctuation.bracket"] = { fg = C.blue },
	["@constructor"] = { fg = C.green },
	["@keyword"] = { fg = C.cyan, style = "italic" },
	["@keyword.return"] = { fg = C.red },
	["@keyword.operator"] = { fg = C.red },
	["@method.call"] = { fg = C.green },
	["@property"] = { fg = C.white },
	["@function"] = { fg = C.green },
	["@operator"] = { fg = C.red, style = "bold" },
	["@constant.builtin"] = { fg = C.magenta },
	["@tag"] = { fg = C.red },
	["@tag.delimiter"] = { fg = C.gray },
	["@tag.attribute"] = { fg = C.cyan },
	["@conditional"] = { fg = C.red },
	["@repeat"] = { fg = C.red },
	["@parameter"] = { fg = C.blue, style = "italic" },
	["@keyword.function"] = { fg = C.cyan, style = "bold,italic" },
	["@number"] = { fg = C.magenta },
	["@boolean"] = { fg = C.magenta },

	-- scss
	["@keyword.scss"] = { fg = C.red },
	["@function.scss"] = { fg = C.cyan },
	["@property.scss"] = { fg = C.green },
	["@string.scss"] = { fg = C.blue, style = "italic" },
	["@number.scss"] = { fg = C.magenta },
	["@type.scss"] = { fg = C.cyan },

	-- cpp
	["@keyword.cpp"] = { fg = C.cyan, style = "italic" },
	["@namespace.cpp"] = { fg = C.white },
	["@operator.cpp"] = { fg = C.red },
	["@type.cpp"] = { fg = C.blue, style = "italic" },
	["@variable.cpp"] = { fg = C.white },
	["@constant.cpp"] = { fg = C.cyan },
	["@constant.macro.cpp"] = { fg = C.red },
	["@punctuation.delimiter.cpp"] = { fg = C.gray },

	-- python
	["@type.python"] = { fg = C.cyan },
	["@keyword.python"] = { fg = C.cyan, style = "italic" },
	["@variable.builtin.python"] = { fg = C.lightGray, style = "italic" },
	["@field.python"] = { fg = C.white },
	["@variable.python"] = { fg = C.white },
	["@constructor.python"] = { fg = C.green },
	["@method.python"] = { fg = C.green },
	["@function.builtin.python"] = { fg = C.cyan, style = "italic" },
	["@exception.python"] = { fg = C.red, style = "italic" },
	["@constant.python"] = { fg = C.magenta },
	["@keyword.function.python"] = { fg = C.cyan, style = "italic" },
	["@operator.python"] = { fg = C.red },
	["@varibale.builtin.python"] = { fg = C.blue, style = "italic" },

	-- lua
	["@variable.lua"] = { fg = C.white },
	["@function.builtin.lua"] = { fg = C.green },
	["@field.lua"] = { fg = C.white },
	["@keyword.lua"] = { fg = C.red, style = "italic" },
	["@keyword.function.lua"] = { fg = C.red },
	["@conditional.lua"] = { fg = C.red },
	["@namespace.lua"] = { fg = C.red },
}

return Treesitter
