local Treesitter = {
	["@include"] = { fg = C.red },
	["@variable"] = { fg = C.white },
	["@punctuation.delimiter"] = { fg = C.lightGray },
	["@punctuation.bracket"] = { fg = C.orange },
	["@constructor"] = { fg = C.green },
	["@keyword"] = { fg = C.cyan, style = "italic" },
	["@keyword.return"] = { fg = C.red },
	["@keyword.operator"] = { fg = C.red },
	["@method.call"] = { fg = C.green },
	["@property"] = { fg = C.white },
	["@function"] = { fg = C.green },
	["@operator"] = { fg = C.red, style = "bold" },
	["@constant.builtin"] = { fg = C.magenta },
	["@tag"] = { fg = C.red },
	["@tag.delimiter"] = { fg = C.gray },
	["@tag.attribute"] = { fg = C.cyan },
	["@conditional"] = { fg = C.red },
	["@repeat"] = { fg = C.red },
	["@parameter"] = { fg = C.orange, style = "italic" },
	["@keyword.function"] = { fg = C.cyan, style = "bold,italic" },
	["@number"] = { fg = C.magenta },
	["@boolean"] = { fg = C.magenta },

	-- TSNONE = { fg = C.base1E },

	["@function.builtin"] = { fg = C.base18 },
	["@variable.builtin"] = { fg = C.base1E },
	["@method"] = { fg = C.base14 },
	["@punctuation.special"] = { fg = C.base0D },
	["@constant"] = { fg = C.base1E },

	["@annotation"] = { fg = C.base18 },
	["@attribute"] = { fg = C.base19 },
	["@type"] = { fg = C.base19 },
	["@type.builtin"] = { fg = C.base19 },
	["@exception"] = { fg = C.base10 },
	["@label"] = { fg = C.base19 },
	["@namespace"] = { fg = C.base19 },
	["@float"] = { fg = C.base15 },
	["@character"] = { fg = C.base12 },
	["@error"] = { fg = C.base0D },
	["@constant.macro"] = { fg = C.base19 },
	["@function.macro"] = { fg = C.base18 },
	["@field"] = { fg = C.base19 },
	["@parameter.reference"] = { fg = C.base19 },
	["@symbol"] = { fg = C.base19 },
	["@text"] = { fg = C.base1F },
	["@string.regex"] = { fg = C.base12 },
	["@string.escape"] = { fg = C.base12 },
	["@text.emphasis"] = { style = "italic" },
	["@text.underline"] = { style = "underline" },
	["@text.title"] = { fg = C.base1F },
	["@text.literal"] = { fg = C.base12 },
	["@text.uri"] = { fg = C.base12, style = "underline" },
	["@text.strong"] = { fg = C.base19, style = "bold" },

	-- scss
	["@keyword.scss"] = { fg = C.red },
	["@function.scss"] = { fg = C.cyan },
	["@property.scss"] = { fg = C.green },
	["@string.scss"] = { fg = C.orange, style = "italic" },
	["@number.scss"] = { fg = C.magenta },
	["@type.scss"] = { fg = C.cyan },

	-- cpp
	["@keyword.cpp"] = { fg = C.cyan, style = "italic" },
	["@namespace.cpp"] = { fg = C.white },
	["@operator.cpp"] = { fg = C.red },
	["@type.cpp"] = { fg = C.orange, style = "italic" },
	["@variable.cpp"] = { fg = C.white },
	["@constant.cpp"] = { fg = C.cyan },
	["@constant.macro.cpp"] = { fg = C.red },
	["@punctuation.delimiter.cpp"] = { fg = C.gray },

	-- python
	["@type.python"] = { fg = C.cyan },
	["@keyword.python"] = { fg = C.cyan, style = "italic" },
	["@variable.builtin.python"] = { fg = C.lightGray, style = "italic" },
	["@field.python"] = { fg = C.white },
	["@variable.python"] = { fg = C.white },
	["@constructor.python"] = { fg = C.green },
	["@method.python"] = { fg = C.green },
	["@function.builtin.python"] = { fg = C.cyan, style = "italic" },
	["@exception.python"] = { fg = C.red, style = "italic" },
	["@constant.python"] = { fg = C.magenta },
	["@keyword.function.python"] = { fg = C.cyan, style = "italic" },
	["@operator.python"] = { fg = C.red },
	["@varibale.builtin.python"] = { fg = C.orange, style = "italic" },

	-- lua
	["@function.builtin.lua"] = { fg = C.base14 },
	["@field.lua"] = { fg = C.base1E },
	["@keyword.lua"] = { fg = C.red },
	["@variable.lua"] = { fg = C.base1E },
	["conditional.lua"] = { fg = C.base0D },
}

return Treesitter
