local winbar = {
	WinbarIconsFile = { fg = "#C5C5C5" },
	WinbarIconsModule = { fg = "#C5C5C5" },
	WinbarIconsNamespace = { fg = "#C5C5C5" },
	WinbarIconsPackage = { fg = "#C5C5C5" },
	WinbarIconsClass = { fg = "#EE9D28" },
	WinbarIconsMethod = { fg = "#B180D7" },
	WinbarIconsProperty = { fg = "#C5C5C5" },
	WinbarIconsField = { fg = "#75BEFF" },
	WinbarIconsConstructor = { fg = "#B180D7" },
	WinbarIconsEnum = { fg = "#EE9D28" },
	WinbarIconsInterface = { fg = "#75BEFF" },
	WinbarIconsFunction = { fg = "#B180D7" },
	WinbarIconsVariable = { fg = "#75BEFF" },
	WinbarIconsConstant = { fg = "#C5C5C5" },
	WinbarIconsString = { fg = "#C5C5C5" },
	WinbarIconsNumber = { fg = "#C5C5C5" },
	WinbarIconsBoolean = { fg = "#C5C5C5" },
	WinbarIconsArray = { fg = "#C5C5C5" },
	WinbarIconsObject = { fg = "#C5C5C5" },
	WinbarIconsKey = { fg = "#C5C5C5" },
	WinbarIconsNull = { fg = "#C5C5C5" },
	WinbarIconsEnumMember = { fg = "#75BEFF" },
	WinbarIconsStruct = { fg = "#C5C5C5" },
	WinbarIconsEvent = { fg = "#EE9D28" },
	WinbarIconsOperator = { fg = "#C5C5C5" },
	WinbarIconsTypeParameter = { fg = "#C5C5C5" },
	WinbarText = { fg = C.winbar_text },
	WinbarSeparator = { fg = C.winbar_separator },
}

return winbar
